/**
 * Generated by orval 🍺
 * Do not edit manually.
 * rust_ssr_example_backend
 * OpenAPI spec version: 0.1.0
 */
import type { FilterModel } from './filterModel';

export type GetRowsRequestFilterModel = {[key: string]: FilterModel};
