/**
 * Generated by orval 🍺
 * Do not edit manually.
 * rust_ssr_example_backend
 * OpenAPI spec version: 0.1.0
 */
import {
  faker
} from '@faker-js/faker';

import {
  HttpResponse,
  http
} from 'msw';
import type {
  RequestHandlerOptions
} from 'msw';

import type {
  StockHistoryGetRowsResponse,
  StockHistoryRow
} from '../models';


export const getListStockHistoryResponseMock = (): StockHistoryRow[] => (Array.from({ length: faker.number.int({min: 1, max: 10}) }, (_, i) => i + 1).map(() => ({close: faker.string.alpha({length: {min: 10, max: 20}}), date: faker.date.past().toISOString().slice(0, 10), high: faker.string.alpha({length: {min: 10, max: 20}}), low: faker.string.alpha({length: {min: 10, max: 20}}), open: faker.string.alpha({length: {min: 10, max: 20}}), ticker: faker.string.alpha({length: {min: 10, max: 20}}), volume: faker.number.int({min: 0})})))

export const getGetRowsResponseMock = (overrideResponse: Partial<Extract<StockHistoryGetRowsResponse, object>> = {}): StockHistoryGetRowsResponse => ({rowCount: faker.number.int(), rowData: Array.from({ length: faker.number.int({min: 1, max: 10}) }, (_, i) => i + 1).map(() => ({close: faker.string.alpha({length: {min: 10, max: 20}}), date: faker.date.past().toISOString().slice(0, 10), high: faker.string.alpha({length: {min: 10, max: 20}}), low: faker.string.alpha({length: {min: 10, max: 20}}), open: faker.string.alpha({length: {min: 10, max: 20}}), ticker: faker.string.alpha({length: {min: 10, max: 20}}), volume: faker.number.int({min: 0})})), ...overrideResponse})


export const getListStockHistoryMockHandler = (overrideResponse?: StockHistoryRow[] | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<StockHistoryRow[]> | StockHistoryRow[]), options?: RequestHandlerOptions) => {
  return http.get('*/api/stock-history', async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getListStockHistoryResponseMock(),
      { status: 200
      })
  }, options)
}

export const getGetRowsMockHandler = (overrideResponse?: StockHistoryGetRowsResponse | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<StockHistoryGetRowsResponse> | StockHistoryGetRowsResponse), options?: RequestHandlerOptions) => {
  return http.post('*/api/stock-history/getRows', async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetRowsResponseMock(),
      { status: 200
      })
  }, options)
}
export const getDomainsStockHistoryRoutesMock = () => [
  getListStockHistoryMockHandler(),
  getGetRowsMockHandler()
]
