/**
 * Generated by orval 🍺
 * Do not edit manually.
 * rust_ssr_example_backend
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  GetRowsRequest,
  StockHistoryGetRowsResponse,
  StockHistoryRow
} from '../models';





const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type listStockHistoryResponse200 = {
  data: StockHistoryRow[]
  status: 200
}

export type listStockHistoryResponse500 = {
  data: void
  status: 500
}

export type listStockHistoryResponseSuccess = (listStockHistoryResponse200) & {
  headers: Headers;
};
export type listStockHistoryResponseError = (listStockHistoryResponse500) & {
  headers: Headers;
};

export type listStockHistoryResponse = (listStockHistoryResponseSuccess | listStockHistoryResponseError)

export const getListStockHistoryUrl = () => {




  return `http://localhost:8000/api/stock-history`
}

export const listStockHistory = async ( options?: RequestInit): Promise<listStockHistoryResponse> => {

  const res = await fetch(getListStockHistoryUrl(),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: listStockHistoryResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as listStockHistoryResponse
}





export const getListStockHistoryQueryKey = () => {
    return [
    `http://localhost:8000/api/stock-history`
    ] as const;
    }


export const getListStockHistoryQueryOptions = <TData = Awaited<ReturnType<typeof listStockHistory>>, TError = void>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listStockHistory>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListStockHistoryQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listStockHistory>>> = ({ signal }) => listStockHistory({ signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listStockHistory>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListStockHistoryQueryResult = NonNullable<Awaited<ReturnType<typeof listStockHistory>>>
export type ListStockHistoryQueryError = void


export function useListStockHistory<TData = Awaited<ReturnType<typeof listStockHistory>>, TError = void>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listStockHistory>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listStockHistory>>,
          TError,
          Awaited<ReturnType<typeof listStockHistory>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListStockHistory<TData = Awaited<ReturnType<typeof listStockHistory>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listStockHistory>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listStockHistory>>,
          TError,
          Awaited<ReturnType<typeof listStockHistory>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListStockHistory<TData = Awaited<ReturnType<typeof listStockHistory>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listStockHistory>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useListStockHistory<TData = Awaited<ReturnType<typeof listStockHistory>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listStockHistory>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListStockHistoryQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type getRowsResponse200 = {
  data: StockHistoryGetRowsResponse
  status: 200
}

export type getRowsResponse400 = {
  data: void
  status: 400
}

export type getRowsResponse500 = {
  data: void
  status: 500
}

export type getRowsResponseSuccess = (getRowsResponse200) & {
  headers: Headers;
};
export type getRowsResponseError = (getRowsResponse400 | getRowsResponse500) & {
  headers: Headers;
};

export type getRowsResponse = (getRowsResponseSuccess | getRowsResponseError)

export const getGetRowsUrl = () => {




  return `http://localhost:8000/api/stock-history/getRows`
}

/**
 * and filter. See https://www.ag-grid.com/react-data-grid/server-side-model-datasource/
 * @summary AG Grid Server-Side Row Model datasource endpoint: infinite scroll, sort
 */
export const getRows = async (getRowsRequest: GetRowsRequest, options?: RequestInit): Promise<getRowsResponse> => {

  const res = await fetch(getGetRowsUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(getRowsRequest)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getRowsResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getRowsResponse
}





export const getGetRowsMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof getRows>>, TError,{data: GetRowsRequest}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof getRows>>, TError,{data: GetRowsRequest}, TContext> => {

const mutationKey = ['getRows'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof getRows>>, {data: GetRowsRequest}> = (props) => {
          const {data} = props ?? {};

          return  getRows(data,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type GetRowsMutationResult = NonNullable<Awaited<ReturnType<typeof getRows>>>
    export type GetRowsMutationBody = GetRowsRequest
    export type GetRowsMutationError = void

    /**
 * @summary AG Grid Server-Side Row Model datasource endpoint: infinite scroll, sort
 */
export const useGetRows = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof getRows>>, TError,{data: GetRowsRequest}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof getRows>>,
        TError,
        {data: GetRowsRequest},
        TContext
      > => {
      return useMutation(getGetRowsMutationOptions(options), queryClient);
    }
